ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      gem install bundler &&
      bundle install --without production &&
      rails db:migrate &&
      yarn install --check-files
    command: >
      rails server
github:
    prebuilds:
        pullRequestsFromForks: true