ports:
  - port: 3000
    onOpen: open-preview
tasks:
  # libldap2-dev and libidn11-dev are required for gem twitter-text due to its dependency on gem idn-ruby
  - init: >
      sudo apt-get install libldap2-dev && 
      sudo apt-get install libidn11-dev && 
      gem install bundler &&
      bundle install --without production &&
      rails db:migrate &&
      yarn install --check-files
    command: >
      rails server
github:
    prebuilds:        
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: false
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # enable for pull requests coming from forks
        pullRequestsFromForks: true
        # add a check to pull requests (defaults to true)
        addCheck: true
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
        addComment: false